name: Google Search Crawler

on:
  workflow_dispatch:
    inputs:
      keywords:
        description: "Comma-separated list of keywords"
        required: false
        default: "apple, banana, cherry"
      keywordsUrl:
        description: "URL to CSV file containing keywords"
        required: false
        default: ""
      
jobs:
  run-crawler:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        npm install

    - name: Run Google Search Crawler
      run: |
        node google-search-crawler.js
      env:
        keywords: ${{ github.event.inputs.keywords }}
        keywordsUrl: ${{ github.event.inputs.keywordsUrl }}
