name: Google Crawler python

on:
  workflow_dispatch:
    inputs:
      id:
        description: "Task ID for result naming"
        required: true
      keywords:
        description: "Comma-separated keywords"
        required: true
      csvFile:
        description: "Base64-encoded CSV file (optional)"
        required: false

jobs:
  run-crawler:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Use Python version 3.9 (or any other version)

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install drissionpage requests pandas

      # Step 4: Decode CSV file if provided
      - name: Decode CSV file
        if: ${{ inputs.csvFile != '' }}
        run: |
          echo "${{ inputs.csvFile }}" | base64 -d > input.csv

      # Step 5: Run the crawler script
      - name: Run crawler
        run: |
          python main.py "${{ inputs.id }}" "${{ inputs.keywords }}" "input.csv"

      # Step 6: Commit and push results
      - name: Commit and push results
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add results/
          git commit -m "Add results for task ID: ${{ inputs.id }}"
          git push
